### ISSUE TITLE
`KeyError: 'INPUT_NAME'`

### ISSUE THREAD

**Issue by fishcharlie** [bettermarks/action-artifact-download#1]
Getting the following error:

```
Traceback (most recent call last):
  File "/app/main.py", line 8, in <module>
    NAME = os.environ["INPUT_NAME"] or ARTIFACT_NAME
  File "/usr/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'INPUT_NAME'
```

My yml action file is as follows:

```
- name: Download Artifact from testrepo
  uses: bettermarks/action-artifact-download@0.1.0
  with:
    repo: fishcharlie/testrepo
    token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    artifact_name: myArtifact
```

**Comment by karfau** [comment]
Is there a reason why you are not using the latest version 0.3.0?

I think our tests are currently not covering the case where the `rename` is not provided, so it might be that this case is also broken in the current version.

As a workaround you might be able to pass the artifact name to the rename property, but I haven't tested that.

Or just use the official https://github.com/actions/download-artifact action, if you do not need the rename feature?

**Comment by fishcharlie** [comment]
@karfau The reason I wasn't using the latest version is because in the README the example code said 0.1.0. And I didn't realize a new version had been released.

I just tested it and 0.3.0 works perfectly.

Maybe the README example can be updated to say 0.3.0 instead of 0.1.0 tho?
